config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  resources :sensors
  resources :stores

  get '/count_entrance/:id' => 'main#count_entrance'
  get '/count_registers' => 'main#count_registers'
  get '/connection_check/:id' => 'main#connection_check'
  get '/reports' => 'main#reports'

  # Reports URIs
  get '/daily_reports' => 'main#daily_reports'
  get '/date_reports' => 'main#date_reports'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/store.rb
class Store < ApplicationRecord
    has_many :sensors
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.all
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to stores_url, notice: 'Tienda creada correctamente' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to stores_url, notice: 'Tienda actualizada correctamente' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'Tienda eliminada correctamente' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :phone, :address)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store, local: true) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
      <% store.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :store_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :store_phone, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, id: :store_address, class: "form-control" %>
  </div>

  <div class="actions">
     <%= form.submit "Aceptar", class: "btn btn-success" %>
     <%= link_to "Cancelar", sensors_url, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<div class="row">
    <div class="col-lg-12">
        <h3 class="main-title">Editar tienda</h3>
        <%= render 'form', store: @store %>        
    </div>
</div>

app/views/stores/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <p id="notice"><%= notice %></p>
  
    <h1 class="main-title">Tiendas</h1>
    
    <%= link_to 'Agregar tienda', new_store_path %>
    
    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Telefono</th>
            <th>Direccion</th>
            <th>Fecha de creacion</th>
            <th colspan="2">Operaciones</th>
          </tr>
        </thead>
      
        <tbody>
          <% @stores.each do |store| %>
            <tr>
              <td><%= store.name %></td>
              <td><%= store.phone %></td>
              <td><%= store.address %></td>
              <td><%= store.created_at %></td>
              <td><%= link_to 'Ver', store %></td>
              <td><%= link_to 'Editar', edit_store_path(store) %></td>
              <!--<td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>  

  </div>
</div>  

app/views/stores/new.html.erb
<div class="row">
    <div class="col-lg-12">
        <h3 class="main-title">Agregar tienda</h3>
        <%= render 'form', store: @store %>        
    </div>
</div>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @store.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @store.address %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>