config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  resources :sensors
  resources :stores

  get '/count_entrance/:id' => 'main#count_entrance'
  get '/count_registers' => 'main#count_registers'
  get '/connection_check/:id' => 'main#connection_check'
  get '/reports' => 'main#reports'

  # Reports URIs
  get '/daily_reports' => 'main#daily_reports'
  get '/date_reports' => 'main#date_reports'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Inicio", "/", :"data-turbolinks" => false, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Tiendas", stores_url, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sensores", sensors_url, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Reportes", '/reports', class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to Time.now, '#', class: "nav-link disabled" %>
      </li>
    </ul>
  </div>
</nav>