config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  resources :sensors
  resources :stores

  get '/count_entrance/:id' => 'main#count_entrance'
  get '/count_registers' => 'main#count_registers'
  get '/connection_check/:id' => 'main#connection_check'
  get '/reports' => 'main#reports'

  # Reports URIs
  get '/daily_reports' => 'main#daily_reports'
  get '/date_reports' => 'main#date_reports'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sensor.rb
class Sensor < ApplicationRecord
  belongs_to :store
  has_many :counters

  def sensor_status
  	if status == 1
  		return "Activo"
  	else
  		return "Inactivo"
  	end
  end

  def self.check_connection
  	Sensor.all.each do |sensor|
      if sensor.connection_request_counter == 0
        sensor.connection_status = false
      end
      sensor.connection_request_counter = 0
  		sensor.save
  	end
  end


end

app/controllers/sensors_controller.rb
class SensorsController < ApplicationController
  before_action :set_sensor, only: [:show, :edit, :update, :destroy]

  # GET /sensors
  # GET /sensors.json
  def index
    @sensors = Sensor.all
  end

  # GET /sensors/1
  # GET /sensors/1.json
  def show
  end

  # GET /sensors/new
  def new
    @sensor = Sensor.new
  end

  # GET /sensors/1/edit
  def edit
  end

  # POST /sensors
  # POST /sensors.json
  def create
    @sensor = Sensor.new(sensor_params)

    respond_to do |format|
      if @sensor.save
        format.html { redirect_to sensors_url, notice: 'Sensor creado correctamente.' }
        format.json { render :show, status: :created, location: @sensor }
      else
        format.html { render :new }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sensors/1
  # PATCH/PUT /sensors/1.json
  def update
    respond_to do |format|
      if @sensor.update(sensor_params)
        format.html { redirect_to sensors_url, notice: 'Sensor actualizado correctamente' }
        format.json { render :show, status: :ok, location: @sensor }
      else
        format.html { render :edit }
        format.json { render json: @sensor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sensors/1
  # DELETE /sensors/1.json
  def destroy
    @sensor.destroy
    respond_to do |format|
      format.html { redirect_to sensors_url, notice: 'Sensor eliminado correctamente' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sensor
      @sensor = Sensor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sensor_params
      params.require(:sensor).permit(:serial_number, :brand, :status, :installation_date, :store_id)
    end
end

app/helpers/sensors_helper.rb
module SensorsHelper
end

app/views/sensors/_form.html.erb
<%= form_with(model: sensor, local: true) do |form| %>
  <% if sensor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sensor.errors.count, "error") %> prohibited this sensor from being saved:</h2>

      <ul>
      <% sensor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label "Numero de serie" %>
    <%= form.text_field :serial_number, id: :sensor_serial_number, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label "Marca" %>
    <%= form.text_field :brand, id: :sensor_brand, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label "Estado" %>
    <%= form.number_field :status, id: :sensor_status, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label "Fecha de instalacion" %>
    <%= form.date_select :installation_date, id: :sensor_installation_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label "Tienda" %>
    <%= form.collection_select :store_id, Store.all, :id, :name, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Aceptar", class: "btn btn-success" %>
    <%= link_to "Cancelar", sensors_url, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/sensors/edit.html.erb
<div class="row">
    <div class="col-lg-12">
        <h3 class="main-title">Editar sensor</h3>
        <%= render 'form', sensor: @sensor %>        
    </div>
</div>

app/views/sensors/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <p id="notice"><%= notice %></p>

    <h1 class="main-title">Sensores</h1>
    
    <%= link_to 'Agregar Sensor', new_sensor_path %>
    
    <div class="table-responsive">
      <table class="table table-hover">
        <thead>
          <tr>
            <th>Numero serialr</th>
            <th>Marca</th>
            <th>Estado</th>
            <th>Conexion con sensores</th>
            <th>Fecha de instalacion</th>
            <th>Tienda</th>
            <th colspan="3">Opciones</th>
          </tr>
        </thead>
      
        <tbody>
          <% @sensors.each do |sensor| %>
            <tr>
              <td><%= sensor.serial_number %></td>
              <td><%= sensor.brand %></td>
              <td><%= sensor.sensor_status %></td>
              <td><%= sensor.connection_status ? "Conectado" : "Desconectado".html_safe %></td>
              <td><%= sensor.installation_date %></td>
              <td><%= sensor.store.name %></td>
              <td><%= link_to 'Editar', edit_sensor_path(sensor) %></td>
              <td><%= link_to 'Eliminar', sensor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>  
  </div>
</div>

app/views/sensors/new.html.erb
<div class="row">
    <div class="col-lg-12">
        <h3 class="main-title">Agregar sensor</h3>
        <%= render 'form', sensor: @sensor %>        
    </div>
</div>

app/views/sensors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Serial number:</strong>
  <%= @sensor.serial_number %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @sensor.brand %>
</p>

<p>
  <strong>Status:</strong>
  <%= @sensor.status %>
</p>

<p>
  <strong>Installation date:</strong>
  <%= @sensor.installation_date %>
</p>

<p>
  <strong>Store:</strong>
  <%= @sensor.store %>
</p>

<%= link_to 'Edit', edit_sensor_path(@sensor) %> |
<%= link_to 'Back', sensors_path %>